version: '3.7'

services:

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: drf-app
    volumes:
      - .:/drf-app
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    container_name: postgres-drf
    environment:
      - POSTGRES_DB=drf-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/postgres-volume/data:/var/lib/postgresql/data
    ports:
      - '5432:5432' 